### ISSUE TITLE
Connection lost on preview

### ISSUE THREAD

**Issue by TomXD** [robsondepaula/unity-android-native-camera#10]
Hi!
It's a promising tool, I could connect my devices, but when I trying to click on the Start Preview button, the connection lost.
I could use saki4510t's plugin, but it doesn't support Explosure settings. Unfortunatly the two plugin is incompatible for build.

**Comment by robsondepaula** [comment]
Hello @TomXD,

It is been a while since I had time to work on this project and it caught my attention that the best is to public archive it.

About your issue, it is common that with new Android versions, fixes need to be made in order for the plugin to work.

Please feel free to fork the project and continue improving it.
