### ISSUE TITLE
Cannot get pixels data from camera Texture

### ISSUE THREAD

**Issue by mileswan** [robsondepaula/unity-android-native-camera#11]
I can run this demo successfully. Now I want get the pixels data from camera Texure but it always return blank data.

I added code like this:
byte[] cameraImage= tex.GetRawTextureData();  
The code in Update(), so it runs in every frame.
The tex is the Texture2D which is created in the function CreateTextureAndPassToPlugin().

I wrote the debug log to show what I get in the byte[] cameraImage( resolution is 1600 * 1200). The log is like this:

 cameraImage size is :7680000, data first 5 bytes is :205205205205205.

It shows that,  the data from the camera texture is never changed.

**Comment by robsondepaula** [comment]
Hi @mileswan,

It is been a while since I had time to work on this project and it caught my attention that the best is to public archive it.

About your issue, it is common that with new Android versions, fixes need to be made in order for the plugin to work.

Please feel free to fork the project and continue improving it.
