### ISSUE TITLE
Record videos using the native camera

### ISSUE THREAD

**Issue by ksyao2002** [robsondepaula/unity-android-native-camera#4]
Hello,

Does this plugin also incorporate the native camera's ability to take pictures and record video? Or does it only take in video feed and put it into a game object? If that's the case, then what's the difference between this and the WebCamTexture that Unity comes with?

Thanks,
Kevin

**Comment by robsondepaula** [comment]
Hi Kevin,

This plugin was not created with this purpose but you could modify it to take pictures and record video since you have access to the Android Camera2 APIs.

Years ago when I was working on this, the WebCamTexture did not provide a way for me to capture the RGB frames so that I could pass to a library that I was using.

If this requirement came to me today, I would prefer starting with https://github.com/Syn-McJ/TFClassify-Unity-Barracuda.
